name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # Cho phép ghi vào repo
  pages: write     # Quyền triển khai Pages
  id-token: write  # Quyền tạo token

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Cần thiết để action gh-pages hoạt động

      - run: npm install && npm run build

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true  # Luôn tạo branch mới